### ISSUE TITLE
Convert Turbo LED GPIO to 3v3 (HIGH)

### ISSUE THREAD

**Issue by arntsonl** [OpenStickFoundation/GP2040-CE#39]
Turbo LED is currently relying on GND rather than 3v3 (HIGH) pin. Reverse the logic to match other board add-ons.

**Comment by TheTrainGoes** [comment]
The choice of Player LEDs being run of 3.3v is likely due to how Brook does theirs and to make it compatible with devices like the BitBangGaming Player LED module.  

Having the turbo LED follow a similar structure will allow it to be more compatible with sticks like the Hori VLX or other units with a single 3.3v line for all onboard LEDs.

**Comment by arntsonl** [comment]
Fixed in 0.5.1 release.
