### ISSUE TITLE
Add support for two player x-input from one board

### ISSUE THREAD

**Issue by quacka6** [OpenStickFoundation/GP2040-CE#92]
I would love to replace my 2 player arcade fighting cabs with ximo and ipac2 with this board.

**Comment by TheTrainGoes** [comment]
Hey @quacka6 ,

There is another community project that addressed this with a 4player board that runs off one input.  

Currently there is a pin limit on the standard Raspberry Pi Pico that would prevent even having two full players worth of inputs (4 directions, 8 main buttons, start + select).

This will be possible should we be able to add a GPIO extension over SPI but until then I am going to close this as out of scope since we have no plans to change the way buttons interact with current GPIO assignment.
